// src/governance/holds.mjs
//
// Reversible lifecycle governance HOLD taxonomy. Reuses C2dHoldError from
// c2d/fs-atomic.mjs so all AutoLoop hold paths share one error class.
// New codes are additive; existing C3B/C3C codes are untouched.

import { C2dHoldError } from "../c2d/fs-atomic.mjs";

export const GOV_HOLD = Object.freeze({
  AUTHORITY_ESCALATION_REJECTED: "HOLD / AUTHORITY_ESCALATION_REJECTED",
  REPAIR_BUDGET_EXHAUSTED: "HOLD / REPAIR_BUDGET_EXHAUSTED",
  REMOTE_BRANCH_DIVERGED: "HOLD / REMOTE_BRANCH_DIVERGED",
  GOVERNANCE_SCOPE_EXPANSION_REQUIRED: "HOLD / GOVERNANCE_SCOPE_EXPANSION_REQUIRED",
  COMMIT_GATE_VIOLATION: "HOLD / COMMIT_GATE_VIOLATION",
  PUSH_GATE_VIOLATION: "HOLD / PUSH_GATE_VIOLATION",
  DRAFT_PR_GATE_VIOLATION: "HOLD / DRAFT_PR_GATE_VIOLATION",
  LIFECYCLE_TRANSITION_INVALID: "HOLD / LIFECYCLE_TRANSITION_INVALID",
  AUTHORIZATION_MISSING: "HOLD / LIFECYCLE_AUTHORIZATION_MISSING",
  AUTHORIZATION_INVALID: "HOLD / LIFECYCLE_AUTHORIZATION_INVALID",
  IRREVERSIBLE_ACTION_BLOCKED: "HOLD / IRREVERSIBLE_ACTION_BLOCKED",
  SECRET_DETECTED: "HOLD / COMMIT_SECRET_DETECTED",
  EVIDENCE_IDENTITY_MISMATCH: "HOLD / EVIDENCE_IDENTITY_MISMATCH",
  REVIEW_UNIT_LIMIT_EXCEEDED: "HOLD / REVIEW_UNIT_LIMIT_EXCEEDED",
  EXTERNAL_REVIEW_RESULT_MISSING: "HOLD / EXTERNAL_REVIEW_RESULT_MISSING",
  EXTERNAL_REVIEW_RESULT_INVALID: "HOLD / EXTERNAL_REVIEW_RESULT_INVALID",
  BUNDLE_PATH_MISMATCH: "HOLD / BUNDLE_PATH_MISMATCH",
  SECURITY_CHECK_INCOMPLETE: "HOLD / SECURITY_CHECK_INCOMPLETE",
  INTEGRATION_GATE_VIOLATION: "HOLD / INTEGRATION_GATE_VIOLATION",
  RESULT_SELF_DECLARATION_REJECTED: "HOLD / RESULT_SELF_DECLARATION_REJECTED",
  REVIEW_UNIT_MEASUREMENT_INCOMPLETE: "HOLD / REVIEW_UNIT_MEASUREMENT_INCOMPLETE",
  WORKTREE_DIRTY_AT_BUNDLE: "HOLD / WORKTREE_DIRTY_AT_BUNDLE",
  CLI_OVERRIDE_REJECTED: "HOLD / CLI_OVERRIDE_REJECTED",
  FRESH_VERIFY_REQUIRED: "HOLD / FRESH_VERIFY_REQUIRED",
  EXTERNAL_REVIEW_RESULT_NOT_CONTROLLER_OWNED: "HOLD / EXTERNAL_REVIEW_RESULT_NOT_CONTROLLER_OWNED",
  PR_NOT_BOUND_TO_PARENT_CARD: "HOLD / PR_NOT_BOUND_TO_PARENT_CARD",
  REMOTE_NOT_AUTHORIZED: "HOLD / REMOTE_NOT_AUTHORIZED",
});

export { C2dHoldError };

export function hold(code, message, details) {
  return new C2dHoldError(code, message, details);
}
