// src/governance/holds.mjs
//
// Reversible lifecycle governance HOLD taxonomy. Reuses C2dHoldError from
// c2d/fs-atomic.mjs so all AutoLoop hold paths share one error class.
// New codes are additive; existing C3B/C3C codes are untouched.

import { C2dHoldError } from "../c2d/fs-atomic.mjs";

export const GOV_HOLD = Object.freeze({
  AUTHORITY_ESCALATION_REJECTED: "HOLD / AUTHORITY_ESCALATION_REJECTED",
  REPAIR_BUDGET_EXHAUSTED: "HOLD / REPAIR_BUDGET_EXHAUSTED",
  REMOTE_BRANCH_DIVERGED: "HOLD / REMOTE_BRANCH_DIVERGED",
  GOVERNANCE_SCOPE_EXPANSION_REQUIRED: "HOLD / GOVERNANCE_SCOPE_EXPANSION_REQUIRED",
  COMMIT_GATE_VIOLATION: "HOLD / COMMIT_GATE_VIOLATION",
  PUSH_GATE_VIOLATION: "HOLD / PUSH_GATE_VIOLATION",
  DRAFT_PR_GATE_VIOLATION: "HOLD / DRAFT_PR_GATE_VIOLATION",
  LIFECYCLE_TRANSITION_INVALID: "HOLD / LIFECYCLE_TRANSITION_INVALID",
  AUTHORIZATION_MISSING: "HOLD / LIFECYCLE_AUTHORIZATION_MISSING",
  AUTHORIZATION_INVALID: "HOLD / LIFECYCLE_AUTHORIZATION_INVALID",
  IRREVERSIBLE_ACTION_BLOCKED: "HOLD / IRREVERSIBLE_ACTION_BLOCKED",
  SECRET_DETECTED: "HOLD / COMMIT_SECRET_DETECTED",
  EVIDENCE_IDENTITY_MISMATCH: "HOLD / EVIDENCE_IDENTITY_MISMATCH",
});

export { C2dHoldError };

export function hold(code, message, details) {
  return new C2dHoldError(code, message, details);
}
